Attempt to guard against failure to get latest version

diff --git a/.github/workflows/homebrew.yml b/.github/workflows/homebrew.yml
--- a/.github/workflows/homebrew.yml
+++ b/.github/workflows/homebrew.yml
@@ -7,6 +7,10 @@ on:
       - completed
   workflow_dispatch:
 
+concurrency:
+  group: ${{ github.workflow }}-${{ github.ref }}
+  cancel-in-progress: true
+
 jobs:
   update-cask:
     runs-on: ubuntu-20.04
@@ -26,6 +30,11 @@ jobs:
           HOMEBREW_TAP_KEY: ${{ secrets.HOMEBREW_TAP_KEY }}
         run: |
           echo "Version ${LATEST} was released at ${LATEST_DATE}"
+
+          if [[ "${LATEST}" == "null" ]]; then
+            echo "Invalid version!"
+            exit 1
+          fi
 
           eval "$(ssh-agent -s)"
           ssh-add - <<< "${HOMEBREW_TAP_KEY}"
diff --git a/.github/workflows/ppa.yml b/.github/workflows/ppa.yml
--- a/.github/workflows/ppa.yml
+++ b/.github/workflows/ppa.yml
@@ -27,6 +27,12 @@ jobs:
           EMAIL: aura@nav.no
         run: |
           echo "Version ${LATEST} was released at ${LATEST_DATE}"
+
+          if [[ "${LATEST}" == "null" ]]; then
+            echo "Invalid version!"
+            exit 1
+          fi
+
           eval "$(ssh-agent -s)"
           ssh-add - <<< "${PPA_REPO_KEY}"
           git clone git@github.com:nais/nais-ppa.git pparepo
@@ -79,6 +85,11 @@ jobs:
         run: |
           echo "Version ${LATEST} was released at ${LATEST_DATE}"
           
+          if [[ "${LATEST}" == "null" ]]; then
+            echo "Invalid version!"
+            exit 1
+          fi
+
           # Fetch latest debs
           wget https://github.com/nais/device/releases/download/${LATEST}/naisdevice.deb -O naisdevice-${LATEST}.deb
           wget https://github.com/nais/device/releases/download/${LATEST}/naisdevice-tenant.deb -O naisdevice-tenant-${LATEST}.deb
diff --git a/.github/workflows/scoop.yml b/.github/workflows/scoop.yml
--- a/.github/workflows/scoop.yml
+++ b/.github/workflows/scoop.yml
@@ -43,6 +43,11 @@ jobs:
         run: |
           echo "Version ${LATEST} was released at ${LATEST_DATE}"
 
+          if [[ "${LATEST}" == "null" ]]; then
+            echo "Invalid version!"
+            exit 1
+          fi
+
           cd bucket
           git config user.email "aura@nav.no"
           git config user.name "naisdevice pipeline"
